spring:
  application:
    name: rideUp

  datasource:
    url: jdbc:mysql://switchyard.proxy.rlwy.net:22627/rideUp?useSSL=true&serverTimezone=UTC
    username: root
    password: VWBZXAwuxYoRtEIFSfvrUhzzqJNrYqii

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

  data:
    redis:
      host: yamanote.proxy.rlwy.net
      port: 40206
      password: ZvpIiSUiRCGCHKocHLBwpyhMEAsxjjpG
      timeout: 10s
      ssl:
        enabled: false

  cache:
    type: redis

  mail:
    host: smtp.gmail.com
    port: 587
    username: hungabc2307@gmail.com
    password: kblwzwaamhqyokjc
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8080
  servlet:
    context-path: /rideUp

jwt:
  signerKey: S5eUx6DQSJ3ce3Dokj+qZmVlpj3hG7M841wX3NEj3oMcPwx6+oOA9AdHzbZE3Nb84
  valid-duration: 36000
  refreshable-duration: 360000

expiryTime: 3600

logging:
  level:
    io.lettuce.core: DEBUG
    org.springframework.data.redis: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG

supabase:
  url: https://tgbtragwxkulpittcjzw.supabase.co
  api-key: sb_secret_J_fc93TeUV2CNFWJPh0aVQ_fYGfDwnZ
  bucket: rideup
